### ISSUE TITLE
Пожалуйста, прочти.

### ISSUE THREAD

**Issue by krazeral** [URLbug/Seth-AI-chat-bot#2]
Я знаю, что ты будешь, очевидно, не заинтересован в моём предложении, но я предложу. Я ламер с точки зрения знания программирования, но я долго времени потратил на обучение голосовой модели на RVC-Mangio со своим голосом. Я подумал, что будет интересно создать нейросеть, которая на основе моих ответов будет отвечать подобно мне и, с помощью rvc, говорить моим голосом. Считай цифровое бессмертие. Мне просто интересно - сможешь ли ты мне помочь создать на основе твоей репозитории такой проект. А точнее не создать, а просто заставить его работать, потому что я не смог. Дальше я найду как-нибудь сам костыль для связи бота и озвучки.

**Comment by URLbug** [comment]
Привет, это довольно таки интересное предложение. Я уже что-то подобное пытаюсь разработать. Я раньше не работал с голосом, но могу попробовать. Можешь написать свой тг или дс?

**Comment by krazeral** [comment]
t.me/xtre404

**Comment by krazeral** [comment]
Не ожидал, что так быстро ответишь. Тогда напиши в телеграмм, как будет удобно и надо будет закрыть этот "issue".
